# C++ compiler
CXX		= $(HOME)/usr/bin/clang++

# llvm-config location
LLVM_CONFIG     = $(HOME)/usr/bin/llvm-config

# Passed to compiler
SRC_DIR		?= $(PWD)
COMMON_FLAGS	= -Wall -O2 -g -std=c++11
LDFLAGS		+= $(shell $(LLVM_CONFIG) --ldflags) -L$(HOME)/usr/bin -lLLVMPolly
CXXFLAGS	+= $(COMMON_FLAGS) $(shell $(LLVM_CONFIG) --cxxflags) -fPIC
CPPFLAGS	+= $(shell $(LLVM_CONFIG) --cppflags) -I$(SRC_DIR)

ifeq ($(shell uname),Darwin)
SHARED_LIB_OPT	= -bundle -undefined dynamic_lookup
else
SHARED_LIB_OPT  = -shared -Wl, -O1
endif

# Installation path
prefix		= ./lib
